steps:
  APPLICATION-13713:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      description: ""
      locationID: ""
      locationName: RAW_AS01_IEAPDTA
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451293
              stepCounter: 13713
            config: {}
            dataType: VARCHAR(4)
            defaultValue: ""
            description: ""
            name: APPLICATION_CODE
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451294
              stepCounter: 13713
            config: {}
            dataType: VARCHAR(30)
            defaultValue: ""
            description: ""
            name: APPLICATION_DESCRIPTION
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451295
              stepCounter: 13713
            config: {}
            dataType: TIMESTAMP_NTZ(6)
            defaultValue: ""
            description: ""
            name: APPLICATION_CREATE_DATE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451296
              stepCounter: 13713
            config: {}
            dataType: VARCHAR(10)
            defaultValue: ""
            description: ""
            name: APPLICATION_CREATE_USERID
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451297
              stepCounter: 13713
            config: {}
            dataType: TIMESTAMP_NTZ(6)
            defaultValue: ""
            description: ""
            name: APPLICATION_LAST_CHG_DATE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451298
              stepCounter: 13713
            config: {}
            dataType: VARCHAR(10)
            defaultValue: ""
            description: ""
            name: APPLICATION_LAST_CHG_USERID
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451299
              stepCounter: 13713
            config: {}
            dataType: DATE
            defaultValue: ""
            description: ""
            name: APPLICATION_EFFECTIVE_DATE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451300
              stepCounter: 13713
            config: {}
            dataType: DATE
            defaultValue: ""
            description: ""
            name: APPLICATION_EXPIRATION_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451301
              stepCounter: 13713
            config: {}
            dataType: VARCHAR(1)
            defaultValue: ""
            description: ""
            name: IEA_APPLICATION
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451302
              stepCounter: 13713
            config: {}
            dataType: VARCHAR(30)
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451303
              stepCounter: 13713
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451304
              stepCounter: 13713
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451305
              stepCounter: 13713
            config: {}
            dataType: VARCHAR(50)
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451306
              stepCounter: 13713
            config: {}
            dataType: VARCHAR(16)
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451307
              stepCounter: 13713
            config: {}
            dataType: VARCHAR(36)
            defaultValue: ""
            description: ""
            name: HVRINTEGSEQ
            nullable: false
            primaryKey: true
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451308
              stepCounter: 13713
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451309
              stepCounter: 13713
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451310
              stepCounter: 13713
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 451311
              stepCounter: 13713
            config: {}
            dataType: VARCHAR(50)
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: false
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('RAW_AS01_IEAPDTA', 'APPLICATION') }}
      name: APPLICATION
      schema: ""
      sqlType: Source
      table: APPLICATION
      type: sourceInput
    stepCounter: "13713"
